services:
  mysql:
    image: mysql:8.4
    container_name: ocean-sentinel-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ocean_sentinel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ocean-sentinel-mysql:/var/lib/mysql

volumes:
  ocean-sentinel-mysql:
